### ISSUE TITLE
Револьвер "инспектор" у уборщика раундстартом

### ISSUE THREAD

**Issue by DreakTheFantom** [imperial-space/space-station14-public#267]
1) Не имею понятия, заспавнился у него раундстартом, говорит что перед раундом никакие настройки не менял(в том числе связанные с персонажем).
2) Сикей: "4eLoVek_krivetka1"
3) Кассиопея, раунд №29490
4) Bagel
5) Увы, не имею

**Comment by Artemvar41** [comment]
Насколько я знаю. Это прикол виззов на день мусора
